version: "3.9"
services:
  web:
    image: eduardogamer78/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    # volumes:
    #   - ./app:/var/www/app
    ports:
      - "82:82" #http
    networks:
      - net_local
    depends_on:
      - mariadb
  
  mariadb:
      image: mariadb
      volumes:
        - ./sail-mariadb:/var/lib/mysql
      ports:
        - "3307:3307"
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=root
        - MYSQL_PASSWORD=run/secrets/MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=run/secrets/MYSQL_ROOT_PASSWORD
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      networks:
        - net_local
      healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
          retries: 3
          timeout: 5s
  
  phpmyadmin:
      image: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - MYSQL_USER=root
        - MYSQL_PASSWORD=run/secrets/MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD=run/secrets/MYSQL_ROOT_PASSWORD
      ports:
        - "8081:80" #http
      depends_on:
        - mariadb
      networks:
        - net_local

secrets:
  mysql_root_password:
    external: true
  mysql_password:
    external: true

networks:
    net_local:
     driver: bridge
volumes:
    sail-mariadb:
     driver: local
