version: "3.9"
services:
  php:
    container_name: php
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '8.2.10-zts-bullseye'
    image: ml-prod
    volumes:
      - ./public:/var/www/app/public
      - ./docker/supervisord:/etc/supervisor/conf.d/
      - ./docker/php/extra-php.ini:/usr/local/etc/php/conf.d/99_extra.ini
      # - ./docker/php/extra-php.ini.semjit:/usr/local/etc/php/conf.d/99_extra.ini
    ports:
      - "80:80" #http
  
  db:
    image: mariadb:10.5.9
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping '-p${DB_PASSWORD}'
      interval: 5s
      retries: 5
  db_admin:
    image: phpmyadmin
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost:8001/
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
volumes:
  db_data:
  db_admin_data:
