version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    # volumes:
    #   - ./app:/var/www/app
    ports:
      - "${PM_PORT}:80" #http
    networks:
      - net_local
    depends_on:
      - mariadb
  
  mariadb:
      image: mariadb
      volumes:
        - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      ports:
        - "${DB_PORT}:3306"
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
      networks:
        - net_local
      healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
          retries: 3
          timeout: 5s
  
  phpmyadmin:
      image: phpmyadmin
      ports:
        - "${PMA_PORT}:80" #http
      environment:
        - PMA_ARBITRARY=1
      depends_on:
        - "${PMA_DB_ENGINE}"
      networks:
        - net_local

networks:
    net_local:
      driver: ${NETWORKS_DRIVER}
volumes:
    mariadb:
      driver: ${VOLUMES_DRIVER}
